# Generated by Django 2.1.2 on 2018-10-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
    ]
