# Generated by Django 2.1.2 on 2018-10-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza_predominante',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id_mascota',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(default='null', max_length=40),
        ),
    ]
