# Generated by Django 2.1.2 on 2018-11-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0007_auto_20181101_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[(1, 'Rescatado'), (2, 'Disponible'), (3, 'Adoptado')], default='null', max_length=40),
        ),
    ]
