# Generated by Django 2.1.2 on 2018-11-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0008_auto_20181101_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Rescatado'), (2, 'Disponible'), (3, 'Adoptado')], default=1),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/Perris/'),
        ),
    ]
