# Generated by Django 2.1.2 on 2018-11-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(default='null', max_length=12, unique=True)),
                ('nombre', models.CharField(default='null', max_length=40)),
                ('apellido', models.CharField(default='null', max_length=40)),
                ('fecha_nac', models.DateField(auto_now=True)),
                ('telefono', models.IntegerField(default=1)),
                ('correo', models.EmailField(default='hola@hola.com', max_length=100)),
                ('tipo_vivienda', models.IntegerField(choices=[(1, 'Seleccione'), (2, 'Departamento'), (3, 'CasaChica'), (4, 'CasaGrande')], default=1)),
                ('comuna', models.IntegerField(choices=[(1, 'Seleccione'), (2, 'SanBernardo'), (3, 'CaleraDeTango'), (4, 'Buin')], default=1)),
                ('password', models.CharField(default='pass', max_length=40)),
            ],
        ),
    ]
